version: '3.8'

services:
  etcd0:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd0
    hostname: etcd0
    environment:
      ETCD_NAME: 'etcd0'
      ETCD_INITIAL_ADVERTISE_PEER_URLS: 'http://etcd0:2380'
      ETCD_LISTEN_PEER_URLS: 'http://0.0.0.0:2380'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd0.etcd:2379'
      ETCD_INITIAL_CLUSTER_TOKEN: 'etcd-cluster-1'
      ETCD_INITIAL_CLUSTER: 'etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380'
      ETCD_INITIAL_CLUSTER_STATE: 'new'
      ALLOW_NONE_AUTHENTICATION: 'yes'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:2379/health']
      interval: 5s
      timeout: 3s
      retries: 10

  etcd1:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd1
    hostname: etcd1
    environment:
      ETCD_NAME: 'etcd1'
      ETCD_INITIAL_ADVERTISE_PEER_URLS: 'http://etcd1:2380'
      ETCD_LISTEN_PEER_URLS: 'http://0.0.0.0:2380'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd1:2379'
      ETCD_INITIAL_CLUSTER_TOKEN: 'etcd-cluster-1'
      ETCD_INITIAL_CLUSTER: 'etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380'
      ETCD_INITIAL_CLUSTER_STATE: 'new'
      ALLOW_NONE_AUTHENTICATION: 'yes'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:2379/health']
      interval: 5s
      timeout: 3s
      retries: 10

  etcd2:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd2
    hostname: etcd2
    environment:
      ETCD_NAME: 'etcd2'
      ETCD_INITIAL_ADVERTISE_PEER_URLS: 'http://etcd2:2380'
      ETCD_LISTEN_PEER_URLS: 'http://0.0.0.0:2380'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd2:2379'
      ETCD_INITIAL_CLUSTER_TOKEN: 'etcd-cluster-1'
      ETCD_INITIAL_CLUSTER: 'etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380'
      ETCD_INITIAL_CLUSTER_STATE: 'new'
      ALLOW_NONE_AUTHENTICATION: 'yes'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:2379/health']
      interval: 5s
      timeout: 3s
      retries: 10

  app1:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      etcd0:
        condition: service_healthy
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
    ports:
      - '3000:3000'
    container_name: app1
    hostname: app1
    environment:
      ETCD_HOSTS: 'http://etcd0:2379,http://etcd1:2379,http://etcd2:2379'

  app2:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      etcd0:
        condition: service_healthy
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
    container_name: app2
    hostname: app2
    environment:
      ETCD_HOSTS: 'http://etcd0:2379,http://etcd1:2379,http://etcd2:2379'

  app3:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      etcd0:
        condition: service_healthy
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
    container_name: app3
    hostname: app3
    environment:
      ETCD_HOSTS: 'http://etcd0:2379,http://etcd1:2379,http://etcd2:2379'
